---
- hosts: all
  become: true
  tasks:
    - name: Add epel repo
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: http://ftp.inf.utfsm.cl/epel/7/x86_64/

    - name: Install nginx
      yum:
        name: nginx
        state: present
