---
- hosts: secundario
  become: true
  tasks:
     - name: Docker compose (postgresql + django)  
       shell: docker-compose up --build -d
       args:
         chdir: /root/inf323-2018-1-group1/docker-compose.yml
       become: True
